blank_issues_enabled: false
contact_links:
    - name: Questions & Discussions
      url: https://github.com/Chevron7Locked/kima/discussions
      about: Ask questions and discuss Kima in GitHub Discussions
